# Generated by Django 4.1 on 2024-02-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Select branch', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.branch', verbose_name='Branch'),
        ),
    ]
